# Day 3 assignment data science

# question 1

In [1]:
import numpy as np

In [2]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# question 2

In [10]:
import numpy as np
list1=[1,2,3,4,5]
list2=[6,7,8,9,2]
arr1=np.array(list1)
arr2=np.array(list2)

print("list1:",list1)
print("list2:",list2)
print("array 1:",arr1)
print("array 2:",arr2)
np.concatenate((arr1,arr2),axis=0)


list1: [1, 2, 3, 4, 5]
list2: [6, 7, 8, 9, 2]
array 1: [1 2 3 4 5]
array 2: [6 7 8 9 2]


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2])

In [7]:
x=np.array([1,2,3,4,5,6,7,8,9,2])
np.sort(x)

array([1, 2, 2, 3, 4, 5, 6, 7, 8, 9])

# question 3

In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print ("array dimension:",arr.ndim)
print ("array size:",arr.size)

[[1 2 3]
 [4 5 6]]
array dimension: 2
array size: 6


# question 4

In [17]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1D ARRAY:",arr1)
rearr=np.reshape(arr1,(-1,2))
print("reshaped 2D:",rearr)

1D ARRAY: [1 2 3 4]
reshaped 2D: [[1 2]
 [3 4]]


In [18]:
import numpy as np
x = np.array([2,5,18,14,4])
y = x[:, np.newaxis]
print(y)

[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


# question 5 

In [23]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,8],[6,7]])
print("vertical stacking: \n",np.vstack((arr1,arr2)))
print("horizontal stacking: \n",np.hstack((arr1,arr2)))

vertical stacking: 
 [[1 2]
 [3 4]
 [5 8]
 [6 7]]
horizontal stacking: 
 [[1 2 5 8]
 [3 4 6 7]]


# question 6

In [24]:
list=[1,1,2,3,4,4,5,6,6]
a_set=set(list)
no_of_unique_values=len(a_set)
print(no_of_unique_values)

6
